version: '3'

services:
  my-redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
    networks: 
      - app-network

  my-postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: 123  # Set your password here
    volumes: 
      - pgdata:/var/lib/postgresql/data
    networks: 
      - app-network

  my-mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    volumes:
      - mongodata:/data/db
    networks:
      - app-network

  app:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - my-postgres
      - my-redis
      - my-mongodb
    networks: 
      - app-network
    
  frontend:
    build:
      context: app/views # Replace with the correct path to your frontend files
      dockerfile: Dockerfile
    ports:
      - 3000:80  # Maps port 80 of the container to local port 3000
    networks:
      - app-network

networks: 
  app-network:
    driver: bridge

volumes:
  pgdata:
  cache:
    driver: local
  mongodata:
    driver: local
