version: '3'

services:
  my-redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks: 
      - app-network

  my-postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
    volumes: 
      - pgdata:/var/lib/postgresql/data
      - /home/ubuntu/workspace/mayo-test/init-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
      - app-network

  my-mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    volumes:
      - mongodata:/data/db
    networks:
      - app-network

  app:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - my-postgres
      - my-redis
      - my-mongodb
    networks: 
      - app-network

  app-front:
    build:
      context: ./frontend/
    ports:
      - 80:80
    depends_on:
      - app
    networks: 
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

networks: 
  app-network:
    driver: bridge

volumes:
  pgdata:
  cache:
  mongodata: