version: '3'

services:

  my-redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
    networks: 
    - app-network

  my-postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    volumes: 
      - pgdata:/var/lib/postgresql/data
    networks: 
      - app-network

  app:
    build:
        context: .
    ports:
      - 8000:8000
    depends_on:
      - my-postgres
      - my-redis
    networks: 
      - app-network
    
  frontend:
    build:
      context: app/views # substitua pelo caminho correto onde estão os arquivos do frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80  # mapeia a porta 80 do container para a porta 3000 local
    networks:
      - app-network

networks: 
  app-network:
    driver: bridge

volumes:
  pgdata:
    external: true
  cache:
    driver: local
